In [1]:
import tensorflow as tf
import numpy as np

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices(np.random.random_sample((10,5,5,3)))
dataset = dataset.shuffle().repeat(2)

conv = tf.layers.convolution2D(128, (5,5), activation='relu')(inputs)
flatten = tf.layers.flatten()(conv)
lin = tf.layers.Dense(10)(flatten)

init = tf.global_variable_initializer()
with tf.Session() as sess:
    sess.run(init)
    sess

In [5]:
data = tf.data.Dataset.from_tensor_slices([2,3,28,9,5])
data = data.shuffle(5).repeat(2)

it = data.make_one_shot_iterator()
nex = it.get_next()

sess = tf.Session()

while True:
    try:
        print((sess.run(nex)))
    except tf.errors.OutOfRangeError:
        break

5
28
9
3
2
9
5
28
3
2


In [6]:
# (ID, class, prediction)

ID = np.array([[2,3],[5,6],[28,2],[6,5],[8,9]], dtype=np.float32)
classes = np.array([1,1,1,2,1], dtype=np.float32)
prediction = np.random.random_sample((5,))


ID_ph = tf.placeholder(ID.dtype, ID.shape)
classes_ph = tf.placeholder(classes.dtype, classes.shape)
prediction_ph = tf.placeholder(prediction.dtype, prediction.shape)

data = tf.data.Dataset.from_tensor_slices((ID_ph, classes_ph, prediction_ph))

data = data.batch(1)


it = data.make_initializable_iterator()
nex = it.get_next()


dense = tf.layers.Dense(10, activation='relu')(nex[0])
pred = tf.layers.Dense(1, activation='sigmoid')(dense)



sess = tf.Session()

init = tf.global_variables_initializer()
sess.run(init)

def update_data(ID, classes, prediction):
    

for _ in range(2):
    sess.run(it.initializer, feed_dict={ID_ph:ID, classes_ph:classes, prediction_ph:prediction})
    while True:
        try:
            print(sess.run(nex[0]))
            val = sess.run(pred)
            
        except tf.errors.OutOfRangeError:
            break

[[2. 3.]]
<class 'numpy.ndarray'>
[[2. 3.]]
<class 'numpy.ndarray'>


In [9]:
np.reshape(np.arange(12),(-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
a = np.arange(10)
print(a.shape)
print(np.expand_dims(a,0).shape)

(10,)
(1, 10)


In [21]:
for i, j in (np.arange(10), np.arange(10)):
    print(i*j)

ValueError: too many values to unpack (expected 2)

In [22]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [25]:
{i:(i*i, 0) for i in range(10)}

{0: (0, 0),
 1: (1, 0),
 2: (4, 0),
 3: (9, 0),
 4: (16, 0),
 5: (25, 0),
 6: (36, 0),
 7: (49, 0),
 8: (64, 0),
 9: (81, 0)}

In [33]:
conc = np.concatenate((np.expand_dims(np.arange(1,11),1), np.expand_dims(np.arange(2,12),1)), axis=1)
print({i:j for i,j in conc})

{1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11}
