In [1]:
import tensorflow as tf
import numpy as np

In [2]:
files = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
filenames = tf.constant(['2', '3'])
labels = tf.constant([1,2])
preds = tf.constant([[1.0,0.0], [0.0,1.0]])

# files_ph = tf.placeholder(files.dtype, files.shape)
# labels_ph = tf.placeholder(labels.dtype, labels.shape)
# preds_ph = tf.placeholder(preds.dtype, preds.shape)

# data = tf.data.Dataset.from_tensor_slices((files, labels))

dic = tf.data.Dataset.from_tensor_slices((files, filenames, labels, preds))
dic_batched = dic.batch(1)

it = dic_batched.make_one_shot_iterator()
nex = it.get_next()

In [14]:
sess = tf.Session()
sess.run(nex)

(array([[1., 2., 3.]], dtype=float32),
 array([1]),
 array([[1., 0.]], dtype=float32))

In [3]:
layer1 = tf.layers.Dense(5)
layer2 = tf.layers.Dense(2)

In [4]:
def _parse(file, filename, label, pred):
    x = layer1(file)
    pred = layer2(x)
    
    return file, filename, label, pred

In [5]:
sess = tf.Session()
sess.run(dic_batched.map(_parse))

TypeError: Fetch argument <MapDataset shapes: ((?, 3), (?,), (?,), (?, 2)), types: (tf.float32, tf.string, tf.int32, tf.float32)> has invalid type <class 'tensorflow.python.data.ops.dataset_ops.MapDataset'>, must be a string or Tensor. (Can not convert a MapDataset into a Tensor or Operation.)